/* tslint:disable */
/* eslint-disable */
/**
 * Auth BFF Service - Terms and Conditions
 * API for user authentication and terms and conditions management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIResponse,
  ErrorResponse,
  LoginRequest,
  LoginResponse,
  TermsAcceptRequest,
  TermsResponse,
} from '../models/index';

export interface AcceptTermsRequest {
    body: TermsAcceptRequest;
}

export interface LoginOperationRequest {
    body: LoginRequest;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * Record that the authenticated user has accepted the terms.
     * @summary Accept terms and conditions
     * @param {TermsAcceptRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    acceptTermsRaw(requestParameters: AcceptTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIResponse>>;

    /**
     * Record that the authenticated user has accepted the terms.
     * Accept terms and conditions
     */
    acceptTerms(requestParameters: AcceptTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIResponse>;

    /**
     * Retrieve terms and conditions content.
     * @summary Retrieve terms and conditions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    getTermsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TermsResponse>>;

    /**
     * Retrieve terms and conditions content.
     * Retrieve terms and conditions
     */
    getTerms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TermsResponse>;

    /**
     * Authenticate user with email and password. Returns session token and user profile.
     * @summary Authenticate user
     * @param {LoginRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    loginRaw(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>>;

    /**
     * Authenticate user with email and password. Returns session token and user profile.
     * Authenticate user
     */
    login(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * Record that the authenticated user has accepted the terms.
     * Accept terms and conditions
     */
    async acceptTermsRaw(requestParameters: AcceptTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling acceptTerms.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/rest/api/v1/auth/terms/accept`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Record that the authenticated user has accepted the terms.
     * Accept terms and conditions
     */
    async acceptTerms(requestParameters: AcceptTermsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIResponse> {
        const response = await this.acceptTermsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve terms and conditions content.
     * Retrieve terms and conditions
     */
    async getTermsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TermsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rest/api/v1/auth/terms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieve terms and conditions content.
     * Retrieve terms and conditions
     */
    async getTerms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TermsResponse> {
        const response = await this.getTermsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Authenticate user with email and password. Returns session token and user profile.
     * Authenticate user
     */
    async loginRaw(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling login.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rest/api/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Authenticate user with email and password. Returns session token and user profile.
     * Authenticate user
     */
    async login(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
