/* tslint:disable */
/* eslint-disable */
/**
 * OneKS Job Info BFF API
 * BFF endpoints for the job-info-details feature — oneks-auth-bff-service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentReviewRequest,
  ErrorResponse,
  GetJobChanges200Response,
  GetJobContracts200Response,
  GetJobInfo200Response,
  JobCancelRequest,
  JobInfoUpdateRequest,
  JobSubmitRequest,
  ReviewContractDocument200Response,
  SubmitJob200Response,
} from '../models/index';

export interface CancelJobRequest {
    jobId: string;
    body: JobCancelRequest;
}

export interface GetJobChangesRequest {
    jobId: string;
    page?: number;
    pageSize?: number;
}

export interface GetJobContractsRequest {
    jobId: string;
}

export interface GetJobInfoRequest {
    jobId: string;
    applicantsPage?: number;
    applicantsPageSize?: number;
}

export interface ReviewContractDocumentRequest {
    jobId: string;
    contractId: string;
    documentId: string;
    body: DocumentReviewRequest;
}

export interface SubmitJobRequest {
    jobId: string;
    body?: JobSubmitRequest;
}

export interface UpdateJobInfoRequest {
    jobId: string;
    body: JobInfoUpdateRequest;
}

/**
 * JobInfoApi - interface
 * 
 * @export
 * @interface JobInfoApiInterface
 */
export interface JobInfoApiInterface {
    /**
     * Cancel the current workflow step (Footer Cancel button). Transitions job status to Cancelled. reason is required.
     * @summary Cancel workflow step
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {JobCancelRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    cancelJobRaw(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitJob200Response>>;

    /**
     * Cancel the current workflow step (Footer Cancel button). Transitions job status to Cancelled. reason is required.
     * Cancel workflow step
     */
    cancelJob(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitJob200Response>;

    /**
     * Fetch paginated change history for the View Changes panel. Returns field-level audit trail sorted by timestamp descending.
     * @summary Get change history
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {number} [page] Page number (1-based)
     * @param {number} [pageSize] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    getJobChangesRaw(requestParameters: GetJobChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobChanges200Response>>;

    /**
     * Fetch paginated change history for the View Changes panel. Returns field-level audit trail sorted by timestamp descending.
     * Get change history
     */
    getJobChanges(requestParameters: GetJobChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobChanges200Response>;

    /**
     * Fetch grouped contract list with document links and per-document review status. Grouped by contractType and cfaType.
     * @summary Get grouped contract list
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    getJobContractsRaw(requestParameters: GetJobContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobContracts200Response>>;

    /**
     * Fetch grouped contract list with document links and per-document review status. Grouped by contractType and cfaType.
     * Get grouped contract list
     */
    getJobContracts(requestParameters: GetJobContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobContracts200Response>;

    /**
     * Fetch full job info including general info, CFA info, loan applicants (paginated), loan details, and collateral. userId is extracted from JWT claims.
     * @summary Get full job info details
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {number} [applicantsPage] Page number for loanApplicants sub-list
     * @param {number} [applicantsPageSize] Page size for loanApplicants sub-list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    getJobInfoRaw(requestParameters: GetJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobInfo200Response>>;

    /**
     * Fetch full job info including general info, CFA info, loan applicants (paginated), loan details, and collateral. userId is extracted from JWT claims.
     * Get full job info details
     */
    getJobInfo(requestParameters: GetJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobInfo200Response>;

    /**
     * Toggle or set the review status on a single contract document. The handler must verify the document belongs to the contract and the job.
     * @summary Mark a contract document as reviewed
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {string} contractId Contract identifier
     * @param {string} documentId Document identifier
     * @param {DocumentReviewRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    reviewContractDocumentRaw(requestParameters: ReviewContractDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewContractDocument200Response>>;

    /**
     * Toggle or set the review status on a single contract document. The handler must verify the document belongs to the contract and the job.
     * Mark a contract document as reviewed
     */
    reviewContractDocument(requestParameters: ReviewContractDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewContractDocument200Response>;

    /**
     * Submit the current workflow step (Footer Submit button). Transitions job status to the next state. Optional comment stored in audit log.
     * @summary Submit workflow step
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {JobSubmitRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    submitJobRaw(requestParameters: SubmitJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitJob200Response>>;

    /**
     * Submit the current workflow step (Footer Submit button). Transitions job status to the next state. Optional comment stored in audit log.
     * Submit workflow step
     */
    submitJob(requestParameters: SubmitJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitJob200Response>;

    /**
     * Update overall info (signing dates, appraisal/selling price) and CFA info fields. Only provided fields are updated (partial update). userId extracted from JWT.
     * @summary Update job info fields
     * @param {string} jobId Job identifier. Format: 3 uppercase letters + 9 digits
     * @param {JobInfoUpdateRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobInfoApiInterface
     */
    updateJobInfoRaw(requestParameters: UpdateJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobInfo200Response>>;

    /**
     * Update overall info (signing dates, appraisal/selling price) and CFA info fields. Only provided fields are updated (partial update). userId extracted from JWT.
     * Update job info fields
     */
    updateJobInfo(requestParameters: UpdateJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobInfo200Response>;

}

/**
 * 
 */
export class JobInfoApi extends runtime.BaseAPI implements JobInfoApiInterface {

    /**
     * Cancel the current workflow step (Footer Cancel button). Transitions job status to Cancelled. reason is required.
     * Cancel workflow step
     */
    async cancelJobRaw(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitJob200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling cancelJob().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling cancelJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}/cancel`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Cancel the current workflow step (Footer Cancel button). Transitions job status to Cancelled. reason is required.
     * Cancel workflow step
     */
    async cancelJob(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitJob200Response> {
        const response = await this.cancelJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch paginated change history for the View Changes panel. Returns field-level audit trail sorted by timestamp descending.
     * Get change history
     */
    async getJobChangesRaw(requestParameters: GetJobChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobChanges200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJobChanges().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}/changes`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Fetch paginated change history for the View Changes panel. Returns field-level audit trail sorted by timestamp descending.
     * Get change history
     */
    async getJobChanges(requestParameters: GetJobChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobChanges200Response> {
        const response = await this.getJobChangesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch grouped contract list with document links and per-document review status. Grouped by contractType and cfaType.
     * Get grouped contract list
     */
    async getJobContractsRaw(requestParameters: GetJobContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobContracts200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJobContracts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}/contracts`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Fetch grouped contract list with document links and per-document review status. Grouped by contractType and cfaType.
     * Get grouped contract list
     */
    async getJobContracts(requestParameters: GetJobContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobContracts200Response> {
        const response = await this.getJobContractsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch full job info including general info, CFA info, loan applicants (paginated), loan details, and collateral. userId is extracted from JWT claims.
     * Get full job info details
     */
    async getJobInfoRaw(requestParameters: GetJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobInfo200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJobInfo().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['applicantsPage'] != null) {
            queryParameters['applicantsPage'] = requestParameters['applicantsPage'];
        }

        if (requestParameters['applicantsPageSize'] != null) {
            queryParameters['applicantsPageSize'] = requestParameters['applicantsPageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Fetch full job info including general info, CFA info, loan applicants (paginated), loan details, and collateral. userId is extracted from JWT claims.
     * Get full job info details
     */
    async getJobInfo(requestParameters: GetJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobInfo200Response> {
        const response = await this.getJobInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Toggle or set the review status on a single contract document. The handler must verify the document belongs to the contract and the job.
     * Mark a contract document as reviewed
     */
    async reviewContractDocumentRaw(requestParameters: ReviewContractDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewContractDocument200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling reviewContractDocument().'
            );
        }

        if (requestParameters['contractId'] == null) {
            throw new runtime.RequiredError(
                'contractId',
                'Required parameter "contractId" was null or undefined when calling reviewContractDocument().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling reviewContractDocument().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling reviewContractDocument().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}/contracts/{contractId}/documents/{documentId}/review`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))).replace(`{${"contractId"}}`, encodeURIComponent(String(requestParameters['contractId']))).replace(`{${"documentId"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Toggle or set the review status on a single contract document. The handler must verify the document belongs to the contract and the job.
     * Mark a contract document as reviewed
     */
    async reviewContractDocument(requestParameters: ReviewContractDocumentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewContractDocument200Response> {
        const response = await this.reviewContractDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit the current workflow step (Footer Submit button). Transitions job status to the next state. Optional comment stored in audit log.
     * Submit workflow step
     */
    async submitJobRaw(requestParameters: SubmitJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitJob200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling submitJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}/submit`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Submit the current workflow step (Footer Submit button). Transitions job status to the next state. Optional comment stored in audit log.
     * Submit workflow step
     */
    async submitJob(requestParameters: SubmitJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitJob200Response> {
        const response = await this.submitJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update overall info (signing dates, appraisal/selling price) and CFA info fields. Only provided fields are updated (partial update). userId extracted from JWT.
     * Update job info fields
     */
    async updateJobInfoRaw(requestParameters: UpdateJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobInfo200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling updateJobInfo().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateJobInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rest/api/v1/jobs/{jobId}`.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update overall info (signing dates, appraisal/selling price) and CFA info fields. Only provided fields are updated (partial update). userId extracted from JWT.
     * Update job info fields
     */
    async updateJobInfo(requestParameters: UpdateJobInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobInfo200Response> {
        const response = await this.updateJobInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
